---
dist: xenial

language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

addons:
  apt:
    packages:
      - musl
      - musl-dev
      - musl-tools

before_install:
  - rustup target add x86_64-unknown-linux-musl
  - cargo install --force cargo-audit

script:
  - cargo audit
  - cargo test --verbose

notifications:
  email:
    on_success: never
    on_failure: never
